Admin10: Deliveries List
Admin1: Customers Registration
Admin2: Employees Registration
Admin3: Branches Registration
Admin4: Add
Admin5: Employees List
Admin6: Go
Admin7: Customers List
Admin8: Branches List
Admin9: Deliveries Registration
Admin: Admin Area
Avenida2: 45 Afonso Pena ave, Macuco - Santos/SP
Avenida: 45 Afonso Pena ave, Macuco
BemVindo: Welcome to our site!
Cadastro1: Registered Users:
Cadastro2: Registered Customers:
Cadastro3: Registered Branches:
Cadastro4: Registered Deliveries:
Cadastro: Fill in the fields
CadastroBtn: Send
Celular: Cell Phone: +55 13 997477862
ChamadaSite: Shipping and deliveries throughout Brazil.
Contato10: Type your message here.
Contato11: Submit
Contato12: Reset
Contato1: Contact us through one of our communication channels and close a deal with us.
Contato2: Our customer service is open Monday to Friday from 8 AM to 18 PM and on Saturdays from 8 AM to 1 PM.
Contato3: Name
Contato4: Email
Contato5: Subject
Contato6: Message
Contato7: Your name
Contato8: user@mydomain.com
Contato9: Subject
Contato: Contact
DeletarBtn: Delete
Endereco: Address:
Entrega: Deliveries
Erro1: The page you are looking for cannot be found.
Erro2: Please wait a few seconds. You will be redirected to our main page.
Erro3: Thank you!
Erro: Sorry,
Estado: Sao Paulo
Facebook: Like our page on Facebook
Filial: Branches
Form1: Customer
Form2: Employee
Form3: Admin
Form4: Type
Form: Registration
Funcionario1: Profile of
Funcionario2: You're logged as
Funcionario: Employee Area
LocalizacaoArea: Real-Time Tracking:
Home1: In the year of our 10th anniversary, we redesigned our website to serve you better.
Home2: Now with a fully responsive website to make it easy for you to access on PC, Notebook, Tablet, mobile phone and other devices.
Home: Home
Localizacao: Location
Login1: Login Area
Login: Authorized Personnel Only
Logout: Logout
LogoutTxt: You have been logged out successfully.
MapaSite: Site Map
Mensagem: Message
Navegacao: Navigation
Nextel: Nextel(ID): 129*20237
Perfil1: Profile of
Perfil2: Login
Perfil3: Password
Perfil4: Branch Profile
Perfil5: Customer Profile
Perfil: User Profile
QuemSomos1: SAUÍPE EXPRESS is a transportation, pick-up and distribution services company acting in Baixada Santista, Grande São Paulo and nationwide, with 10+ experience helping small, medium and big business from all economy sectors.
QuemSomos2: Our Mission
QuemSomos3: Our goal is to help all-sized business in need of agility and reliability regarding orders and documents transportation through a 24/7 motorcycle delivery, so that packages are delivered safely, quickly and efficiently to their final destination.
QuemSomos4: SPEED, RESPONSABILITY AND TRUST
QuemSomos5: This is our business. Be our partner!
QuemSomos6: 45 Afonso Pena ave, Macuco - Santos, Sao Paulo
QuemSomos: About Us
Servicos10: Occasional
Servicos11: Express delivery of small parcels across the city, this service caters to individuals and companies with speed and quality. The pricing is previously defined according to the table of locations, depending on the distance.
Servicos12: Contact us for details on this kind of service.
Servicos1: By hiring our services, you will speed up your deliveries and handovers of courier packages, bills, invoices, banking services, small and medium volumes, among others, with total speed and security for we’ve got a specialized team for each type of service, catering to the needs of each client in various segments, such as:
Servicos2: industries, banks, financial institutions, medical offices, dealerships, accounting offices, law firms, drugstores, restaurant, takeouts and any company seeking a definite and economical solution in urgent transport.
Servicos3: Monthly
Servicos4: We provide your company one or more motorcycle couriers in uniform and equipped with cellphones or radio communication that will serve your company in any type of external services at the times established in contract.
Servicos5: Full-time
Servicos6: Monday to friday, 8 hours/day.
Servicos7: Part-time (morning)
Servicos8: 4h/day
Servicos9: P.S.: In case of unforeseen circumstances, replacement of the driver or vehicle will be arranged at most within 90 minutes.
Servicos: Business
Sucesso: Your form was successfully submitted!
Telefone2: Contact number:
Telefone: Phone:+55 13 32239211 or +55 13 32245876
TxtAcao: Remove
TxtCargo: Job Title
TxtCidade: City
TxtCliente: Customer
TxtCnpj: CNPJ
TxtCpf: CPF
TxtData: Date
TxtEmail: Email
TxtEndereco: Address
TxtFilial: Branch
TxtFuncionario: Motoboy
TxtLogin: Login:
TxtNascimento: Birthday
TxtNome: Name
TxtSenha: Password:
TxtContato: Contact
TxtTelefone: Contact Number
Voltar: Go Back