Admin1: Cadastro de Cliente
Admin2: Cadastro de Funcionário
Admin3: Cadastro de Administrador
Admin4: Adicionar
Admin5: Lista de Funcionários
Admin6: Ir
Admin: Área do Administrador
Avenida: Av. Afonso Pena, 45 - Macuco,
Avenida2: Av. Afonso Pena, 45 - Macuco, Santos - SP
BemVindo: Seja Bem Vindo ao nosso site!
Cadastro: Preencha o cadastro.
CadastroBtn: Cadastrar
Celular: Celular: (13) 99747-7862
ChamadaSite: Frete e entregas para todo o Brasil.
Contato10: Digite sua mensagem
Contato11: Enviar
Contato12: Limpar
Contato1: Entre em contato conosco por meio de um dos nossos canais de comunicação e feche negócio com a gente.
Contato2: Nossa central de atendimento funciona de segunda a sexta-feira das 8h às 18h e aos sábados das 8h às 13h.
Contato3: Nome
Contato4: Email
Contato5: Assunto
Contato6: Mensagem
Contato7: Digite seu nome
Contato8: Digite seu email
Contato9: Digite o assunto
Contato: Contato
DeletarBtn: Deletar 
Endereco: Endereço:
Erro1: A página que você digitou não existe ou está fora do ar.
Erro2: Por favor aguarde alguns segundos, você será redirecionado para nossa página principal.
Erro3: Obrigada!
Erro: Desculpe,
Estado: SP
Facebook: Curta nossa página no facebook
Form: Cadastro de 
Form1: Cliente 
Form2: Funcionário 
Form3: Administrador  
Funcionario1: Perfil de
Funcionario2: Você está logado como
Funcionario: Área do Funcionário
Home1: No ano que fazemos nosso aniversário de 10 anos, reformulamos nosso site para melhor atendê-lo.
Home2: Agora com o site totalmente responsivo, facilitando seu acesso através do Computador, Notebook, Tablet, celular e demais dispositivos móveis
Home: Início
Localizacao: Localização
Login1: Preencha os campos abaixo:
Login: Acesso Restrito
Logout: Sair
LogoutTxt: Você foi deslogado com sucesso.
MapaSite: Mapa do Site
Navegacao: Navigacao
Nextel: Nextel(ID): 129*20237  
Perfil: Perfil do Usuário 
Perfil1: Perfil de
Perfil2: Login 
Perfil3: Senha 
QuemSomos1: A SAUÍPE EXPRESS é uma empresa especializada em serviços de transportes, coletas e distribuição, que atua na Baixada Santista e Grande São Paulo e também em todo território nacional, com uma experiência de mais de 10 anos atendendo pequenas, médias e grandes empresas, dos mais diversos segmentos da economia.
QuemSomos2: Missão da Empresa
QuemSomos3: Nosso objetivo é atender empresas e particulares de todo porte, que precisam de agilidade e confiança no transporte de documentos e encomendas com motoboy 24 horas, 7 dias semanais para que suas entregas e distribuições cheguem ao destino final de forma segura, rápida e eficiente, facilitando assim a vida do nosso cliente.
QuemSomos4: RAPIDEZ, RESPONSABILIDADE e CONFIANÇA.
QuemSomos5: Este é o nosso negócio. Seja nosso parceiro você também!
QuemSomos6: Av. Afonso Pena, 45 - Macuco, Santos – SP
QuemSomos: Quem Somos
Servicos10: Esporádico
Servicos11: Serviços de entregas rápidas de encomendas leves de um ponto para o outro da cidade, este serviço atende a pessoas físicas e jurídicas com rapidez e qualidade. O valor do serviço é definido previamente de acordo com a tabela de localidades, em função da distância.
Servicos12: Entre em contato conosco e veja os detalhes deste tipo de serviço.
Servicos1: Ao contratar os nossos serviços você agilizará suas entregas e retiradas de malotes, duplicatas, notas fiscais, serviços, bancários, pequenos e médios volumes, entre outros, com total rapidez e segurança, pois contamos com uma equipe especializada para cada tipo de serviço. Nós personalizamos o atendimento para a necessidade de cada cliente em diversos segmentos como:
Servicos2: indústrias, bancos, financeiras, consultórios, concessionárias, contabilidades, advocacias, farmácias, restaurantes, deliverys e todos estabelecimentos ou empresas que buscam uma solução definitiva e econômica em transportes urgentes.
Servicos3: Mensal
Servicos4: Colocamos à disposição de sua empresa um ou mais motofretistas, uniformizados e equipados com CELULAR ou RADIOCOMUNICAÇÃO que servirão a sua empresa em qualquer tipo de serviço externo nos horários determinados em contrato.
Servicos5: Integral
Servicos6: Segunda à sexta-feira, jornada de 8h/dia.
Servicos7: Meio Período (Manhã)
Servicos8: Jornada de 4h/dia
Servicos9: Obs.: Em caso de algum imprevisto, a substituição do condutor ou veículo será efetuada em no máximo 90 minutos.
Servicos: Serviços
Sucesso: Cadastrado com sucesso!
Telefone: Telefone: (13) 3223-9211 ou 3224-5876
Telefone2: Telefones para contato:
TxtNome: Nome: 
TxtLogin: Login: 
TxtSenha: Senha: 
Voltar: Voltar